version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  admin:
    build:
      context: ./backend
      dockerfile: Dockerfile.admin
    ports:
      - "8501:8501"
    volumes:
      - ./backend:/app
    command: ["streamlit", "run", "admin.py", "--server.port=8501", "--server.enableCORS=false"]